php:
  build: ./
  environment:
    - |
      FRX_APT_GET_INSTALL=
      libfreetype6-dev
      libgd-dev
      libjpeg62-turbo-dev
      libpng-dev
    - |
      FRX_PHP_EXT_CONFIGURE=
      gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
    - |
      FRX_PHP_EXT_INSTALL=
      gd
      pdo_mysql
    - |
      FRX_PHP_INI=
      date.timezone = "Europe/Paris"
      post_max_size = 10M
      upload_max_filesize = 10M
      log_errors = true
      error_log = /var/log/php.log
    - |
      FRX_APACHE_ENABLE_MOD=
      rewrite