name: Build and publish Docker images

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-8.0.yml
      - ./build/**
      - ./php8.0/**

jobs:
  build-docker-php80:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # PHP 8.0
      - name: Build and push - frxyt/php-dev:8.0-apache
        uses: docker/build-push-action@v2
        with:
          context: ./php8.0/Dockerfile-apache
          push: true
          tags: |
            frxyt/php-dev:8.0
            frxyt/php-dev:8.0-apache
            frxyt/php-dev:8.0-apache-buster
      - name: Build and push - frxyt/php-dev:8.0-cli
        uses: docker/build-push-action@v2
        with:
          context: ./php8.0/Dockerfile-cli
          push: true
          tags: |
            frxyt/php-dev:8.0-cli
            frxyt/php-dev:8.0-cli-buster
      - name: Build and push - frxyt/php-dev:8.0-fpm
        uses: docker/build-push-action@v2
        with:
          context: ./php8.0/Dockerfile-fpm
          push: true
          tags: |
            frxyt/php-dev:8.0-fpm
            frxyt/php-dev:8.0-fpm-buster