name: Build Docker images for PHP 8.1

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-8.1.yml
      - build/**
      - php8.1/**
  workflow_dispatch:

jobs:
  build-docker-php81:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # PHP 8.1
      - name: Build and push - frxyt/php-dev:8.1-apache
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php8.1/Dockerfile-apache
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            frxyt/php-dev:8.1
            frxyt/php-dev:8.1-apache
            frxyt/php-dev:8.1-apache-bullseye
      - name: Build and push - frxyt/php-dev:8.1-cli
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php8.1/Dockerfile-cli
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            frxyt/php-dev:8.1-cli
            frxyt/php-dev:8.1-cli-bullseye
      - name: Build and push - frxyt/php-dev:8.1-fpm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php8.1/Dockerfile-fpm
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            frxyt/php-dev:8.1-fpm
            frxyt/php-dev:8.1-fpm-bullseye