name: Build and publish Docker images

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-7.4.yml
      - ./build/**
      - ./php7.4/**

jobs:
  build-docker-php74:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # PHP 7.4
      - name: Build and push - frxyt/php-dev:7.4-apache
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php7.4/Dockerfile-apache
          push: true
          tags: |
            frxyt/php-dev:latest
            frxyt/php-dev:7.4
            frxyt/php-dev:7.4-apache
            frxyt/php-dev:7.4-apache-buster
      - name: Build and push - frxyt/php-dev:7.4-cli
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php7.4/Dockerfile-cli
          push: true
          tags: |
            frxyt/php-dev:7.4-cli
            frxyt/php-dev:7.4-cli-buster
      - name: Build and push - frxyt/php-dev:7.4-fpm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php7.4/Dockerfile-fpm
          push: true
          tags: |
            frxyt/php-dev:7.4-fpm
            frxyt/php-dev:7.4-fpm-buster